<div class="content">
    <div class="content byEditor about">
        <h3>Understanding the History of the Patrick Geddes Archives</h3>
        <p>Many of the historic papers of Patrick Geddes are now housed in the Archives and Special Collections services of the Universities of Edinburgh and Strathclyde. The history of the collections is complex, each having been in the care of multiple custodians and subject to multiple physical relocations before reaching their current home at the Universities of Edinburgh and Strathclyde. Information on the history of the collections will help you to understand their provenance and allow you to use them more easily.</p>
        <p>Additional material is held in private hands or in other institutions. You can find out what is held elsewhere on our Research Resources [insert link to research resources] page.</p>
        <h3>What will you find in the collections?</h3>
        <figure  class="right-image"><a href="https://images.is.ed.ac.uk/luna/servlet/iiif/UoEgal~5~5~163832~373738/full/full/0/default.jpg" title="View of the Lawnmarket and High Street, Edinburgh from Patrick Geddes’ Outlook Tower, c. 1914 (Ref: GB237 Coll-1167/B/27/1/8)" target="_blank"><img src="https://images.is.ed.ac.uk/luna/servlet/iiif/UoEgal~5~5~163832~373738/full/200,/0/default.jpg" alt-text="View of the Lawnmarket and High Street, Edinburgh from Patrick Geddes’ Outlook Tower, c. 1914 (Ref: GB237 Coll-1167/B/27/1/8)"/></a><figcaption>View of the Lawnmarket and High Street, Edinburgh from Patrick Geddes’ <em>Outlook Tower</em>, c. 1914 (Ref: GB237 Coll-1167/B/27/1/8)</figcaption></figure>
        <p>In 1892, Patrick Geddes purchased a six-storey building on Edinburgh&rsquo;s Royal Mile. He developed this once public observatory into a civic museum; an education tool aimed at the urban planner and the citizen. He named it the <em>Outlook Tower</em>. Here, Geddes amassed a vast collection of maps, views, plans, architectural drawings, photographs and other visual images. The <em>Outlook Tower</em> collections included his <em>Survey of Edinburgh</em>, (commenced in the early 1890s) and material from his early exhibitions in Paris (1900), Glasgow (1901) and London (1910). Geddes&rsquo; <em>Cities and Town Planning Exhibition</em> (first displayed in London in February 1911) emerged from the collections at the <em>Outlook Tower</em>. Between 1911 and 1914, Geddes toured his <em>Cities and Town Planning Exhibition</em> around the United Kingdom, Ireland and Europe including visits to Edinburgh, Dublin, Belfast, Ghent and Paris. Composed of over 4000 exhibits, the original <em>Cities and Town Planning Exhibition</em> was lost at sea on board the <em>SS Clan Grant</em>, during transit to India in 1914. A replacement exhibition was assembled under the direction of Geddes&rsquo; colleague the architect, Henry Vaughan Lanchester (1863-1953), and shipped to India in December 1914.</p>
        <p>It is this replacement exhibition, including material relating to Geddes&rsquo; <em>Survey of Edinburgh</em>, that makes up much of the surviving collections material at both the Universities of Edinburgh and Strathclyde. Additional papers at the University of Strathclyde Archives and Special Collections, brought together by Patrick Geddes’ youngest son Arthur Geddes (1895-1968) include textual records, pamphlets, books, maps, plans, photographs, prints and drawings relating to all of Geddes’ life and work up until his death in 1932.</p>
        <h3>Why are the collections physically separate?</h3>
        <p>Patrick Geddes toured the <em>Cities and Town Planning Exhibition</em> around India during his 10 years there between 1914 and 1924. Throughout his time in India, Geddes surveyed over 30 Indian cities as he fulfilled multiple requests for advice on city improvements. He served as the inaugural Chair of Sociology and Civics at the then University of Bombay from 1919 to 1924.</p>
        <figure  class="left-image"><a href="https://images.is.ed.ac.uk/luna/servlet/iiif/UoEgal~5~5~155823~211379/full/full/0/default.jpg" title="Patrick Geddes sitting outside his Scots’ College, Montpellier, France, c. 1930 (Ref: GB237 Coll-1869/1/17)" target="_blank"><img src="https://images.is.ed.ac.uk/luna/servlet/iiif/UoEgal~5~5~155823~211379/full/200,/0/default.jpg" alt-text="Patrick Geddes sitting outside his Scots’ College, Montpellier, France, c. 1930 (Ref: GB237 Coll-1869/1/17)"/></a><figcaption>Patrick Geddes sitting outside his <em>Scots&rsquo; College</em>, Montpellier, France, c. 1930 (Ref: GB237 Coll-1869/1/17)</figcaption></figure>
        <p class = "by-image">Geddes relocated to Montpellier, France, in 1924. Here he founded the <em>Scots&rsquo; College</em> and he remained in Montpellier until his death in 1932. In 1927, the <em>Cities and Town Planning Exhibition</em> was boxed in tea chests and shipped from India to the <em>Scots&rsquo; College</em> in Montpellier. After Geddes&rsquo; death, his son Arthur Geddes arranged for these tea chests, containing the exhibition, to be sent to London in 1947. These were to be inspected by town planner Jaqueline Tyrwhitt (1905-1983) on behalf of the Association for Planning and Regional Reconstruction (APRR; an affiliate of the Town Planning Institute) with a view to purchasing the material. At this time, additional material which had been stored at More&rsquo;s Garden, Patrick Geddes&rsquo; University Settlement in Chelsea, was selected by Tyrwhitt to be re-united with the material arriving from France. The APRR did not purchase the collection, although in November 1948, Tyrwhitt along with Professor Sir George Pepler (1882-1959), town planner, organised an exhibition in London with selected illustrations from Geddes&rsquo; <em>Cities and Town Planning Exhibition</em>. This meant that in 1948, collections material was to be found across at least four locations: More&rsquo;s Garden, University College London, on loan to Pepler and Tyrwhitt, and at the <em>Outlook Tower</em>. Between 1948 and 1954 collections at the <em>Outlook Tower</em> were temporarily removed to allow refurbishment work to take place. In the early 1950s, Arthur Geddes, a lecturer in geography at the University of Edinburgh, undertook a visiting professorship to the University of California. He selected sample material from the collections at the <em>Outlook Tower</em> and took it with him to California in the hope that the University of California would purchase the <em>Cities and Town Planning Exhibition</em>. Between 1947 and 1955 the collections had been subject to multiple relocations and significant dispersal. Much damage to the exhibits seems to have happened at this stage, according to a statement of losses and assets drawn up around 1955 by the <em>Outlook Tower</em> Association (founded by Arthur Geddes in 1948).</p>
        <p>Material from the Tyrwhitt and Pepler exhibition was placed in the care of the University of Edinburgh&rsquo;s Professor Percy Johnson Marshall (1915-1993), town planner and newly appointed senior lecturer at the University&rsquo;s School of Architecture. The remaining material was sold by the Trustees of the <em>Outlook Tower</em> in 1955 to Dr Thomas Findlay Lyon (1911-1973), a lecturer in town planning at the Royal Technical College, Glasgow. The Royal Technical College was succeeded by the University of Strathclyde in 1964.</p>
        <h3>The University of Edinburgh Collections</h3>
        <p>In 1949, the <em>Outlook Tower</em> was sold by the Town and Gown Association to Castlehill Properties Ltd, a trust which included members of the Geddes family. Percy Johnson-Marshall and Professor Robert Matthew created the School of Architecture at the University of Edinburgh in 1959, in which they developed a course in Civic Design. The intention was to repair and restore the <em>Outlook Tower</em> in which could be housed a newly formed Patrick Geddes Centre for Planning Studies for the University of Edinburgh. In order to allow refurbishment work to proceed, Johnson-Marshall together with the Castlehill Properties Trust arranged for the archive collections to be cleared from the <em>Outlook Tower</em> and stored temporarily in University of Edinburgh premises. Some material appears to have been lost at this stage and, undoubtedly, further losses are likely to have occurred as a result of multiple subsequent moves. Between 1959 and 1989 the Patrick Geddes archives were relocated no less than 8 times, including spending a number of years concealed in the bricked-up attic of 58 George Square, Edinburgh. The Patrick Geddes Archives returned to the Patrick Geddes Centre for Planning Studies at the <em>Outlook Tower</em> in 1989, with the exception of a small proportion of collections material which was placed with the then Royal Commission for Ancient and Historic Monuments for Scotland (succeeded by Historic Environment Scotland). From 1989, the Patrick Geddes Archives remained at the Patrick Geddes Centre for Planning at the <em>Outlook Tower</em> until its transfer to the University of Edinburgh Archives and Special Collections in &hellip;.</p>
        <p>An additional accession of Geddes family photographs was accepted from the Geddes family in about 2000.</p>
        <h3>The University of Strathclyde Collections</h3>
        <p>A proportion of the Patrick Geddes archives were sold to the Royal Technical College, Glasgow in 1955. The Royal Technical College merged with the Scottish College of Commerce and together they received
            a Royal Charter to become the University of Strathclyde in 1964. Two years later, in 1966, the Patrick Geddes archives were moved to new premises at University of Strathclyde&rsquo;s School of Architecture. During this move a proportion of the, then unlisted, collection was accidentally lost. In 1968-69, the Department of Urban Planning became responsible for the collection before it was finally placed with the newly established University Archives in 1977.</p>
        <h3>Cataloguing History</h3>
        <figure  class="left-image"><a href="https://cantaloupe.is.ed.ac.uk/iiif/2/geddes-history-photo-cat.png/full/full/0/default.jpg" title="A sample of the Geddes family photographs catalogued during the ‘Evergreen’ project."
                                        target="_blank"><img src="https://cantaloupe.is.ed.ac.uk/iiif/2/geddes-history-photo-cat.png/full/200,/0/default.jpg" alt-text="A sample of the Geddes family photographs catalogued during the ‘Evergreen’ project."/></a>
            <figcaption>A sample of the Geddes family photographs catalogued during the ‘Evergreen’ project.</figcaption></figure>
        <p>The Papers of Patrick Geddes at both the Universities of Edinburgh and Strathclyde have previously been the subject of multiple listing and cataloguing projects. During the 1970s and 1980s, some early listings were undertaken by non-specialist staff and pre-date the development of professional archival cataloguing standards. Other later cataloguing efforts utilised extensive specialist and research knowledge and contain much invaluable descriptive content. Various methods of arrangement were adopted across both collections. The University of Strathclyde collections suffer from not having been sorted thoroughly prior to cataloguing work commencing in 1979. The collections there follow a subject oriented classification but this was applied inconsistently. It was difficult to implement given Geddes’ interdisciplinary and multidisciplinary ethos, and due to the confusing history of the collections. The University of Edinburgh collections arrangement largely reflects the physical layout of Geddes&rsquo; <em>Cities and Town Planning Exhibition</em>. Multiple legacy catalogues exist.</p>
        <figure  class="right-image"><a href="https://cantaloupe.is.ed.ac.uk/iiif/2/geddes-history-bundles-1.png/full/full/0/default.jpg" title="A sample of a bundle of letters catalogued during the ‘Evergreen’ project."
                                        target="_blank"><img src="https://cantaloupe.is.ed.ac.uk/iiif/2/geddes-history-bundles-1.png/full/200,/0/default.jpg" alt-text="A sample of a bundle of letters catalogued during the ‘Evergreen’ project"/></a>
            <figcaption>A sample of a bundle of letters catalogued during the ‘Evergreen’ projectt.</figcaption></figure>
        <p>On assessing the collections in 2016, we found that some parts of the Papers of Patrick Geddes were richly and accurately described, while other parts were not. It was not possible to undertake a wholesale re-working of all legacy catalogues within the confines of the &lsquo;Evergreen&rsquo; project. The original collections arrangements have been maintained. We focussed on retro-converting legacy printed catalogues to a single electronic data-set; enhancing existing descriptions often by identifying previously mis-identified or unidentified correspondents; created item level descriptions for material that had previously only been listed as bundles (bundles often contained in excess of 200 items) and making all of the revised catalogue content available online via a shared resource. Occasionally we had to apply new or altered catalogue reference numbers.</p>
        <p>In 2020, as we come to the end of the &lsquo;Evergreen&rsquo; project, some work remains to be done to complete the itemised cataloguing of bundles and to enhance some existing descriptions. Beyond the end of the &lsquo;Evergreen&rsquo; project, new and enhanced descriptions will continue to be added to the archive catalogues and the online shared resource will be updated as necessary.</p>
        <h3>Acknowledgements</h3>
        <p>Information regarding the custodial history of the collections was compiled from the writings of Dr Sofia G. Leonard (former Director of the Patrick Geddes for Planning Studies), Professor Volker M. Welter (architectural historian) and Jim McGrath (former University Archivist, University of Strathclyde). Dr Leonard, Professor Welter and Marion Geddes (among many others) were also very generous with their time when interviewed. Their extensive knowledge of and enthusiasm for Patrick Geddes has helped us to piece together the most comprehensive custodial history of the collections to date.</p>
        <p>Read more about the custodial history of the collections:</p>
        <p>Volker M. Welter, &lsquo;Stages of an Exhibition: The <em>Cities and Town Planning Exhibition</em> of Patrick Geddes&rsquo;, in Planning History, Vol 20, No 1, 1998 <a href="https://intlplanninghistorysociety.files.wordpress.com/2014/07/1998_vol-20_no1.pdf" target="_blank" title = "Planning History">https://intlplanninghistorysociety.files.wordpress.com/2014/07/1998_vol-20_no1.pdf</a> </p>
        <p>Sofia G. Leonard, The Papers of Professor Sir Patrick Geddes from the <em>Outlook Tower</em>, Edinburgh: Catalogue of the Archives of the Patrick Geddes Centre for Planning Studies, Vol I, Introduction, pp. 1-10. file://ds.strath.ac.uk/home/djb16224/Downloads/H1167%20(5).pdf</p>
    </div>
</div>