FROM centos:6.10

RUN yum -y install epel-release httpd openssh-clients
RUN rpm -Uvh http://rpms.famillecollet.com/enterprise/remi-release-6.rpm
RUN yum -y --enablerepo=remi-php73 install php php-common.x86_64 php-xml.x86_64 php-xmlrpc.x86_64 php-cli.x86_64 php-mysql.x86_64 php-pdo.x86_64
# see https://tecadmin.net/nstall-php7-on-centos6/

# Overwrite Apache2 conf
COPY skylight-local/docker/httpd.conf /etc/httpd/conf/

# Add skylight conf to sites available
COPY skylight-local/docker/virtualhost.conf /etc/httpd/conf/

# Expose port 80 in container
EXPOSE 80

# Run Apache2 as main process
ENTRYPOINT ["/usr/sbin/httpd", "-D", "FOREGROUND"]

# ssh -4 -N -f -L 9122:127.0.0.1:8080 dspace@lac-repo-test14.is.ed.ac.uk
# docker run -it -p 8080:80 -v /home/hrafn/PhpstormProjects/skylight:/var/html/www/skylight -v /home/hrafn/PhpstormProjects/skylight-local:/var/html/www/skylight-local eerc_skylight
