<div class="col-md-9 col-sm-9 col-xs-12">
    <div class="content byEditor">
        <h1 class="itemtitle">Regional Ethnology Scotland Archive Project</h1>

        <img src="<?php echo base_url()?>/theme/eerc/images/thumbs_processed/thumbnail_DG8-1-4-4.JPG" alt="Interviews of Isobel Sutherland aged 57" width="300" class="img-responsive pull-right padded_images" />
        <img src="<?php echo base_url()?>/theme/eerc/images/thumbs_processed/thumbnail_DG11-1-4-2.JPG" alt="Interviews of Nancy McLucas, Christine Wilson and Eric Wilson" width="300" class="img-responsive pull-right padded_images" style="margin-top: 1em; clear:both;" />
        <img src="<?php echo base_url()?>/theme/eerc/images/eerc_logo.png" alt="European Etnological Research Centre" width="250" class="img-responsive pull-right padded_images" style="margin-top: 1em; clear:both;" />
        <img src="<?php echo base_url()?>/theme/eerc/images/CRC_logo.gif" alt="Centre for Research Collections" width="150" class="img-responsive pull-right padded_images" style="margin-top: 1em; clear:both;" />

        <p>The EERC has been working with the <a href="https://www.ed.ac.uk/information-services/library-museum-gallery/cultural-heritage-collections/crc" target="_new">Centre for Research Collections at the University of Edinburgh</a> since 2018 cataloguing and digitally preserving a collection centred around hundreds of audio recordings and developing and building an on-line platform to aid the discovery of the RESP Archive and ensure its long term preservation and stability.</p>

        <p>The Project’s initial aim was to catalogue a series of around 300 audio interviews generated by the first phase of the RESP, which was carried out in Dumfries and Galloway. Central to the ethos of RESP is the ability to make the collections freely available for study, teaching and research. The project therefore quickly grew to incorporate the development of a user interface where all digital audio files can be accessed and photographs and transcripts viewed, in one place.</p>

        <p>It has been our aim to develop a platform which is both user friendly, to allow full and easy interrogation of the collections, and also ensures the long term preservation and stability of the archive. The partnership between the EERC and the CRC means that we have been able to combine the complementary skills of the ethnologists with the curatorial knowledge of CRC archivists and also, very importantly, the development skills of the Digital Library team. The project has a dedicated Archivist and Archives Assistant who work alongside a Systems Developer who has built the user interface and created a dedicated digital preservation system. We have also been working with the CRC’s Digital Archivist who is creating an acquisitions procedure which will ensure a streamlined and sustainable workflow to allow for on-going and sustainable long-term ingest of material.</p>

        <p>The initial stages of the project were focused on development and piloting both the digital preservation system and the user interface alongside catalogue content creation and screening. The first collection is now available to explore and enjoy and we will continue to add content over time as existing collections are prepared for release and new collections are created.</p>

        <p>For further information on the processes behind the development of our Archive project, our digital preservation strategy or if you would simply like to learn more about the project, you can consult the documents attached.</p>

        <p>This RESP Archive and this website are the result of an ongoing collaboration between the Centre for Research Collections (CRC) and the EERC, University of Edinburgh. The RESP Archive is managed and maintained as a University of Edinburgh Collection.</p>

        <p><strong>RESP Archive Team</strong>:</p>

        <ul class="content">
            <li>Lesley Bryson, Archivist (CRC)</li>

            <li>Caroline Milligan, Archives Assistant (CRC/EERC)</li>

            <li>Mark Mulhern, Senior Research Fellow (EERC)</li>
        </ul>

        <img src="<?php echo base_url()?>/theme/eerc/images/resp-handwriting.png" alt="Part of a handwritten transcription from an interview" class="img-responsive center-block padded_images" style="margin-top: 1em; clear:both;" />

        <p>Enquiries regarding the RESP Archive should be directed in the first instance to: <a href="mailto:is-crc@ed.ac.uk">is-crc@ed.ac.uk</a> Please address your enquiry to ‘<i>RESP Archive</i>’.</p>

        <img src="<?php echo base_url()?>/theme/eerc/images/partnerships-resp.jpg" alt="Partnerships" width="300" class="img-responsive pull-right padded_images" style="margin-top: 1em; clear:both;" />

        <p><strong>Partnerships</strong></p>

        <p>RESP material is created by the EERC in partnership with a number of collaborating partners.</p>

        Institutional Partnerships

        <ul class="content">
            <li>Local Studies and Archives Development, Dumfries and Galloway Council</li>
        </ul>

        Group Partnerships

        <ul class="content">
            <li><a href="http://www.stranraerhistory.org.uk/" target="_new">Stranraer and District Local History Trust</a></li>

            <li><a href="https://www.peterpanmoatbrae.org/" target="_new">Peter Pan Moat Brae Trust</a></li>

            <li>Kirkcudbright Harbour Cottage Trust</li>
        </ul>

        <img src="<?php echo base_url()?>/theme/eerc/images/books_resp.jpg" alt="People holding books" class="img-responsive center-block padded_images" style="margin-top: 2em; margin-bottom: 2em; clear:both;" />

    </div>
</div>
