<div class="col-xs-12 col-md-10 col-md-offset-1 col-lg-6 col-lg-offset-3 intro">

    <div class="intro-text">
        <p><strong><span data-contrast="auto">Privacy policy</span></strong><span data-ccp-props="{&quot;201341983&quot;:0,&quot;335559739&quot;:160,&quot;335559740&quot;:259}">&nbsp;</span></p>
        <p><strong><span data-contrast="auto">Information on UMIS&nbsp;</span></strong><span data-ccp-props="{&quot;201341983&quot;:0,&quot;335559739&quot;:160,&quot;335559740&quot;:259}">&nbsp;</span></p>
        <p><span data-contrast="auto">To find out about UMIS, please contact us at:</span><span data-ccp-props="{&quot;201341983&quot;:0,&quot;335559739&quot;:160,&quot;335559740&quot;:259}">&nbsp;</span></p>
        <p><span data-contrast="auto">University Museums in Scotland</span><span data-ccp-props="{&quot;201341983&quot;:0,&quot;335559739&quot;:160,&quot;335559740&quot;:259}">&nbsp;</span></p>
        <p><span data-contrast="auto">c/o The Hunterian at Kelvin Hall</span><span data-ccp-props="{&quot;201341983&quot;:0,&quot;335559739&quot;:160,&quot;335559740&quot;:259}">&nbsp;</span></p>
        <p><span data-contrast="auto">1445 Argyle Street</span><span data-ccp-props="{&quot;201341983&quot;:0,&quot;335559739&quot;:160,&quot;335559740&quot;:259}">&nbsp;</span></p>
        <p><span data-contrast="auto">Glasgow&nbsp;</span><span data-ccp-props="{&quot;201341983&quot;:0,&quot;335559739&quot;:160,&quot;335559740&quot;:259}">&nbsp;</span></p>
        <p><span data-contrast="auto">G3 8AW</span><span data-ccp-props="{&quot;201341983&quot;:0,&quot;335559739&quot;:160,&quot;335559740&quot;:259}">&nbsp;</span></p>
        <p><span data-contrast="auto">Or </span><a href="mailto:sarah.burry-hayes@glasgow.ac.uk"><span data-contrast="none"><span data-ccp-charstyle="Hyperlink">email us</span></span></a><span data-ccp-props="{&quot;201341983&quot;:0,&quot;335559739&quot;:160,&quot;335559740&quot;:259}">&nbsp;</span></p>
        <p><strong><span data-contrast="auto">Personal information and retention</span></strong><span data-ccp-props="{&quot;201341983&quot;:0,&quot;335559739&quot;:160,&quot;335559740&quot;:259}">&nbsp;</span></p>
        <p><span data-contrast="auto">We will only ever collect the information that we need. If we ever ask you to provide personal </span><span data-contrast="auto">data</span><span data-contrast="auto"> we will make sure you fully understand why we&rsquo;re asking and how we will use this information. We will only ever keep information for as long as required for the purpose it was collected.</span><span data-ccp-props="{&quot;201341983&quot;:0,&quot;335559739&quot;:160,&quot;335559740&quot;:259}">&nbsp;</span></p>
        <p><strong><span data-contrast="auto">Using our website</span></strong><span data-ccp-props="{&quot;201341983&quot;:0,&quot;335559739&quot;:160,&quot;335559740&quot;:259}">&nbsp;</span></p>
        <p><span data-contrast="auto">To ensure your experience of visiting the UMIS site is as easy as possible for you</span><span data-contrast="auto">, we will sometimes place small amounts of information on your computer. These are called cookies and are used by </span><span data-contrast="auto">most</span><span data-contrast="auto"> websites</span><span data-contrast="auto">. For more information, see our cookie policy &lt;&lt;link out&gt;&gt;</span><span data-ccp-props="{&quot;201341983&quot;:0,&quot;335559739&quot;:160,&quot;335559740&quot;:259}">&nbsp;</span></p>
        <p><strong><span data-contrast="auto">Third parties</span></strong><span data-ccp-props="{&quot;201341983&quot;:0,&quot;335559739&quot;:160,&quot;335559740&quot;:259}">&nbsp;</span></p>
        <p><span data-contrast="auto">We will never disclose your personal data to any other organisation.</span><span data-ccp-props="{&quot;201341983&quot;:0,&quot;335559739&quot;:160,&quot;335559740&quot;:259}">&nbsp;</span></p>
        <p><strong><span data-contrast="none"><span data-ccp-parastyle="heading 3">Your rights</span></span></strong><span data-ccp-props="{&quot;201341983&quot;:0,&quot;335559738&quot;:40,&quot;335559739&quot;:0,&quot;335559740&quot;:259}">&nbsp;</span></p>
        <p><span data-contrast="none"><span data-ccp-parastyle="Normal (Web)">UMIS</span></span><span data-contrast="none"><span data-ccp-parastyle="Normal (Web)"> would like to make sure you are fully aware of your data protection rights. Every user is entitled to the following:</span></span><span data-ccp-props="{&quot;134233117&quot;:true,&quot;134233118&quot;:true,&quot;201341983&quot;:0,&quot;335559740&quot;:240}">&nbsp;</span></p>
        <p><strong><span data-contrast="none"><span data-ccp-charstyle="Strong">The right to access</span></span></strong><span data-contrast="none"><span data-ccp-parastyle="Normal (Web)"> &ndash; You have the right to request </span></span><span data-contrast="none"><span data-ccp-parastyle="Normal (Web)">UMIS</span></span><span data-contrast="none"><span data-ccp-parastyle="Normal (Web)"> for copies of your personal data. We may charge you a small fee for this service.</span></span><span data-ccp-props="{&quot;134233117&quot;:true,&quot;134233118&quot;:true,&quot;201341983&quot;:0,&quot;335559740&quot;:240}">&nbsp;</span></p>
        <p><strong><span data-contrast="none"><span data-ccp-charstyle="Strong">The right to rectification</span></span></strong><span data-contrast="none"><span data-ccp-parastyle="Normal (Web)"> &ndash; You </span></span><span data-contrast="none"><span data-ccp-parastyle="Normal (Web)">have</span></span><span data-contrast="none"><span data-ccp-parastyle="Normal (Web)"> the right to request that </span></span><span data-contrast="none"><span data-ccp-parastyle="Normal (Web)">UMIS</span></span><span data-contrast="none"><span data-ccp-parastyle="Normal (Web)"> correct any information you believe is inaccurate. You also have the right to request Our Company to complete the information you believe is incomplete.</span></span><span data-ccp-props="{&quot;134233117&quot;:true,&quot;134233118&quot;:true,&quot;201341983&quot;:0,&quot;335559740&quot;:240}">&nbsp;</span></p>
        <p><strong><span data-contrast="none"><span data-ccp-charstyle="Strong">The right to erasure</span></span></strong><span data-contrast="none"><span data-ccp-parastyle="Normal (Web)"> &ndash; You </span></span><span data-contrast="none"><span data-ccp-parastyle="Normal (Web)">have</span></span><span data-contrast="none"><span data-ccp-parastyle="Normal (Web)"> the right to request that </span></span><span data-contrast="none"><span data-ccp-parastyle="Normal (Web)">UMIS</span></span><span data-contrast="none"><span data-ccp-parastyle="Normal (Web)"> erase your personal data, under certain conditions.</span></span><span data-ccp-props="{&quot;134233117&quot;:true,&quot;134233118&quot;:true,&quot;201341983&quot;:0,&quot;335559740&quot;:240}">&nbsp;</span></p>
        <p><strong><span data-contrast="none"><span data-ccp-charstyle="Strong">The right to restrict processing</span></span></strong><span data-contrast="none"><span data-ccp-parastyle="Normal (Web)"> &ndash; You have the right to request that </span></span><span data-contrast="none"><span data-ccp-parastyle="Normal (Web)">UMIS</span></span><span data-contrast="none"><span data-ccp-parastyle="Normal (Web)"> restrict the processing of your personal data, under certain conditions.</span></span><span data-ccp-props="{&quot;134233117&quot;:true,&quot;134233118&quot;:true,&quot;201341983&quot;:0,&quot;335559740&quot;:240}">&nbsp;</span></p>
        <p><strong><span data-contrast="none"><span data-ccp-charstyle="Strong">The right to object to processing</span></span></strong><span data-contrast="none"><span data-ccp-parastyle="Normal (Web)"> &ndash; You have the right to object to </span></span><span data-contrast="none"><span data-ccp-parastyle="Normal (Web)">UMIS&rsquo;s</span></span><span data-contrast="none"><span data-ccp-parastyle="Normal (Web)"> processing of your personal data, under certain conditions.</span></span><span data-ccp-props="{&quot;134233117&quot;:true,&quot;134233118&quot;:true,&quot;201341983&quot;:0,&quot;335559740&quot;:240}">&nbsp;</span></p>
        <p><strong><span data-contrast="none"><span data-ccp-charstyle="Strong">The right to data portability</span></span></strong><span data-contrast="none"><span data-ccp-parastyle="Normal (Web)"> &ndash; You </span></span><span data-contrast="none"><span data-ccp-parastyle="Normal (Web)">have</span></span><span data-contrast="none"><span data-ccp-parastyle="Normal (Web)"> the right to request that </span></span><span data-contrast="none"><span data-ccp-parastyle="Normal (Web)">UMIS</span></span><span data-contrast="none"><span data-ccp-parastyle="Normal (Web)"> transfer the data that we have collected to another organization, or directly to you, under certain conditions.</span></span><span data-ccp-props="{&quot;134233117&quot;:true,&quot;134233118&quot;:true,&quot;201341983&quot;:0,&quot;335559740&quot;:240}">&nbsp;</span></p>
        <p><span data-contrast="none"><span data-ccp-parastyle="Normal (Web)">If you would like to exercise any of these rights, please </span></span><a href="mailto:sarah.burry-hayes@glasgow.ac.uk"><span data-contrast="none"><span data-ccp-charstyle="Hyperlink">email us</span></span></a><span data-contrast="none"><span data-ccp-parastyle="Normal (Web)"> or write to us at:</span></span><span data-ccp-props="{&quot;134233117&quot;:true,&quot;134233118&quot;:true,&quot;201341983&quot;:0,&quot;335559740&quot;:240}">&nbsp;</span></p>
        <p><span data-ccp-props="{&quot;134233117&quot;:true,&quot;134233118&quot;:true,&quot;201341983&quot;:0,&quot;335559740&quot;:240}">&nbsp;</span></p>
        <p><span data-contrast="auto">University Museums in Scotland</span><span data-ccp-props="{&quot;201341983&quot;:0,&quot;335559739&quot;:160,&quot;335559740&quot;:259}">&nbsp;</span></p>
        <p><span data-contrast="auto">c/o The Hunterian at Kelvin Hall</span><span data-ccp-props="{&quot;201341983&quot;:0,&quot;335559739&quot;:160,&quot;335559740&quot;:259}">&nbsp;</span></p>
        <p><span data-contrast="auto">1445 Argyle Street</span><span data-ccp-props="{&quot;201341983&quot;:0,&quot;335559739&quot;:160,&quot;335559740&quot;:259}">&nbsp;</span></p>
        <p><span data-contrast="auto">Glasgow&nbsp;</span><span data-ccp-props="{&quot;201341983&quot;:0,&quot;335559739&quot;:160,&quot;335559740&quot;:259}">&nbsp;</span></p>
        <p><span data-contrast="auto">G3 8AW</span><span data-ccp-props="{&quot;201341983&quot;:0,&quot;335559739&quot;:160,&quot;335559740&quot;:259}">&nbsp;</span></p>
        <p><strong><span data-contrast="auto"><span data-ccp-parastyle="heading 3">Changes to our privacy policy</span></span></strong><span data-ccp-props="{&quot;201341983&quot;:0,&quot;335559738&quot;:40,&quot;335559739&quot;:0,&quot;335559740&quot;:259}">&nbsp;</span></p>
        <p><span data-contrast="auto"><span data-ccp-parastyle="Normal (Web)">UMIS</span></span><span data-contrast="auto"><span data-ccp-parastyle="Normal (Web)"> keeps its privacy policy under regular review and places any updates on this web page. This privacy policy was last updated on </span></span><span data-contrast="auto"><span data-ccp-parastyle="Normal (Web)">15 January 2020</span></span><span data-contrast="auto"><span data-ccp-parastyle="Normal (Web)">.</span></span><span data-ccp-props="{&quot;134233117&quot;:true,&quot;134233118&quot;:true,&quot;201341983&quot;:0,&quot;335559740&quot;:240}">&nbsp;</span></p>
        <p><strong><span data-contrast="auto">Cookies policy</span></strong><span data-ccp-props="{&quot;201341983&quot;:0,&quot;335559739&quot;:160,&quot;335559740&quot;:259}">&nbsp;</span></p>
        <p><strong><span data-contrast="auto"><span data-ccp-parastyle="heading 3">What are cookies?</span></span></strong><span data-ccp-props="{&quot;201341983&quot;:0,&quot;335559738&quot;:40,&quot;335559739&quot;:0,&quot;335559740&quot;:259}">&nbsp;</span></p>
        <p><span data-contrast="auto"><span data-ccp-parastyle="Normal (Web)">This website uses cookies. </span></span><span data-contrast="auto"><span data-ccp-parastyle="Normal (Web)">Cookies </span></span><span data-contrast="auto"><span data-ccp-parastyle="Normal (Web)">are small text files placed on your computer, </span></span><span data-contrast="auto"><span data-ccp-parastyle="Normal (Web)">or other internet enabled device such as a tablet or phone</span></span><span data-contrast="auto"><span data-ccp-parastyle="Normal (Web)"> when you browse this website. They are used to remember when your computer or device accesses the </span></span><span data-contrast="auto"><span data-ccp-parastyle="Normal (Web)">UMIS </span></span><span data-contrast="auto"><span data-ccp-parastyle="Normal (Web)">w</span></span><span data-contrast="auto"><span data-ccp-parastyle="Normal (Web)">e</span></span><span data-contrast="auto"><span data-ccp-parastyle="Normal (Web)">bsite.</span></span><span data-ccp-props="{&quot;134233117&quot;:true,&quot;134233118&quot;:true,&quot;201341983&quot;:0,&quot;335559740&quot;:240}">&nbsp;</span></p>
        <p><strong><span data-contrast="auto"><span data-ccp-parastyle="heading 3">How do we use cookies?</span></span></strong><span data-ccp-props="{&quot;201341983&quot;:0,&quot;335559738&quot;:40,&quot;335559739&quot;:0,&quot;335559740&quot;:259}">&nbsp;</span></p>
        <p><span data-contrast="auto"><span data-ccp-parastyle="Normal (Web)">UMIS mostly</span></span><span data-contrast="auto"><span data-ccp-parastyle="Normal (Web)"> uses cookies </span></span><span data-contrast="auto"><span data-ccp-parastyle="Normal (Web)">to understand how you use our website. </span></span><span data-contrast="none"><span data-ccp-parastyle="Normal (Web)">We will retain and evaluate information on your </span></span><span data-contrast="none"><span data-ccp-parastyle="Normal (Web)">visit</span></span><span data-contrast="none"><span data-ccp-parastyle="Normal (Web)"> to our website and how you move around different sections of our website for analytics purposes to understand how people use our website so that we can make it more intuitive</span></span><span data-contrast="none"><span data-ccp-parastyle="Normal (Web)">.</span></span><span data-ccp-props="{&quot;134233117&quot;:true,&quot;134233118&quot;:true,&quot;201341983&quot;:0,&quot;335559740&quot;:240}">&nbsp;</span></p>
        <p><strong><span data-contrast="auto"><span data-ccp-parastyle="Normal (Web)">What information do we collect?</span></span></strong><span data-ccp-props="{&quot;134233117&quot;:true,&quot;134233118&quot;:true,&quot;201341983&quot;:0,&quot;335559740&quot;:240}">&nbsp;</span></p>
        <p><span data-contrast="auto"><span data-ccp-parastyle="Normal (Web)">Our cookies aren&rsquo;t used to identify </span></span><span data-contrast="auto"><span data-ccp-parastyle="Normal (Web)">you</span></span><span data-contrast="auto"><span data-ccp-parastyle="Normal (Web)"> personally and don&rsquo;t collect your name, address or your contact details</span></span><span data-contrast="auto"><span data-ccp-parastyle="Normal (Web)">. Instead, they&rsquo;re used purely to find out how easily you are navigating our site.</span></span><span data-ccp-props="{&quot;134233117&quot;:true,&quot;134233118&quot;:true,&quot;201341983&quot;:0,&quot;335559740&quot;:240}">&nbsp;</span></p>
        <p><span data-contrast="auto"><span data-ccp-parastyle="Normal (Web)">You can always delete </span></span><span data-contrast="auto"><span data-ccp-parastyle="Normal (Web)">cookies </span></span><span data-contrast="auto"><span data-ccp-parastyle="Normal (Web)">or set your browser not to accept them</span></span><span data-contrast="auto"><span data-ccp-parastyle="Normal (Web)">. For more information on how to manage, control or delete files, visit </span></span><a href="http://www.aboutcookies.org/"><span data-contrast="none"><span data-ccp-charstyle="Hyperlink">www.aboutcookies.org</span></span></a><span data-contrast="auto"><span data-ccp-parastyle="Normal (Web)">&nbsp;</span></span><span data-ccp-props="{&quot;134233117&quot;:true,&quot;134233118&quot;:true,&quot;201341983&quot;:0,&quot;335559740&quot;:240}">&nbsp;</span></p>
        <p><strong><span data-contrast="auto"><span data-ccp-parastyle="Normal (Web)">What types of cookies do we use?</span></span></strong><span data-ccp-props="{&quot;134233117&quot;:true,&quot;134233118&quot;:true,&quot;201341983&quot;:0,&quot;335559740&quot;:240}">&nbsp;</span></p>
        <p><strong><span data-contrast="auto"><span data-ccp-parastyle="Normal (Web)">&lt;&lt;The below is taken from the Go Industrial website &ndash; can you check these are also the ones that UMIS uses? Obviously the google analytics ones are standard.</span></span></strong><strong><span data-contrast="auto"><span data-ccp-parastyle="Normal (Web)">&gt;&gt;</span></span></strong><span data-ccp-props="{&quot;134233117&quot;:true,&quot;134233118&quot;:true,&quot;201341983&quot;:0,&quot;335559740&quot;:240}">&nbsp;</span></p>
        <table data-tablestyle="MsoNormalTable" data-tablelook="1184">
            <tbody>
            <tr>
                <td data-celllook="69905">
                    <p><strong><span data-contrast="none">Cookie Name</span></strong><span data-ccp-props="{&quot;201341983&quot;:0,&quot;335559740&quot;:240}">&nbsp;</span></p>
                </td>
                <td data-celllook="69905">
                    <p><strong><span data-contrast="none">Description</span></strong><span data-ccp-props="{&quot;201341983&quot;:0,&quot;335559740&quot;:240}">&nbsp;</span></p>
                </td>
                <td data-celllook="69905">
                    <p><strong><span data-contrast="none">Duration / Expires</span></strong><span data-ccp-props="{&quot;201341983&quot;:0,&quot;335559740&quot;:240}">&nbsp;</span></p>
                </td>
            </tr>
            <tr>
                <td data-celllook="69905">
                    <p><span data-contrast="none">PHPSESSID</span><span data-ccp-props="{&quot;201341983&quot;:0,&quot;335559740&quot;:240}">&nbsp;</span></p>
                </td>
                <td data-celllook="69905">
                    <p><span data-contrast="none">Logging of a user looking at the site</span><span data-ccp-props="{&quot;201341983&quot;:0,&quot;335559740&quot;:240}">&nbsp;</span></p>
                </td>
                <td data-celllook="69905">
                    <p><span data-contrast="none">When the browsing session ends</span><span data-ccp-props="{&quot;201341983&quot;:0,&quot;335559740&quot;:240}">&nbsp;</span></p>
                </td>
            </tr>
            <tr>
                <td data-celllook="69905">
                    <p><span data-contrast="none">_</span><span data-contrast="none">ga</span><span data-ccp-props="{&quot;201341983&quot;:0,&quot;335559740&quot;:240}">&nbsp;</span></p>
                </td>
                <td data-celllook="69905">
                    <p><span data-contrast="none">Google Analytics tracking code</span><span data-ccp-props="{&quot;201341983&quot;:0,&quot;335559740&quot;:240}">&nbsp;</span></p>
                </td>
                <td data-celllook="69905">
                    <p><span data-contrast="none">48 hours after first visit</span><span data-ccp-props="{&quot;201341983&quot;:0,&quot;335559740&quot;:240}">&nbsp;</span></p>
                </td>
            </tr>
            </tbody>
        </table>

    </div>
</div>